config/routes.rb
Events::Application.routes.draw do
  resources :events
  match '/posters' => 'events#gallery', as: :gallery, via: :get

  root to: 'events#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :end, :name, :poster, :start

  mount_uploader :poster, PosterUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
#encoding: utf-8
class EventsController < ApplicationController
  # GET /posters
  # GET /posters.json
  def gallery
    @posters = Event.select("poster, id").where("poster <> ?", "")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posters }
    end
  end

  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Wydarzenie zostało utworzone!' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Wydarzenie zostało uaktualnione.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(name, title="")
    raw "<i class='icon-#{name}'></i> #{title}"  
  end
end

app/views/events/_form.html.erb
<%= simple_form_for @event, :html => { :class => 'form-horizontal well' } do |f| %>
  <%= f.input :name, hint: "Podaj nazwę dla nowego wydarzenia" %>
  <%= f.input :poster %>
  <%= f.input :description, hint: "Opisz swoje wydarzenie w samych superlatywach!" %>
  <%= f.input :start %>
  <%= f.input :end %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to "Anuluj",
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="page-header">
  <h1><%= icon "edit", "Edytuj wydarzenie" %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/gallery.html.erb
<div class="row">
  <div class="span3 offset3">
    <%= link_to icon("download","POBIERZ GALERIĘ"), "#", id: "get_gallery", class: "btn btn-large btn-success" %>
  </div>
</div>

<div class="row" id="gallery_content">
  <div class="span1">
    <%= link_to icon("chevron-left icon-3x"), "#", id: "prev_image" %>
    <%= link_to icon("chevron-right icon-3x"), "#", id: "next_image" %>
  </div>
  <div class="span8" id="image_content">
  </div>
</div>

app/views/events/index.html.erb
<div class="page-header">
  <h1>Wszystkie wydarzenia</h1>
</div>
<% if @events.blank? %>
  <p>Brak danych</p>
<% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nazwa</th>
        <th>Start</th>
        <th>Koniec</th>
        <th>Utworzono</th>
      </tr>
    </thead>
    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td>
            <% if event.poster_url %>
              <%= image_tag event.poster_url(:minithumb), class: "img-polaroid" %>
            <% else %>
              <%= image_tag "minithumb.jpg", class: "img-polaroid" %>
            <% end %>
            <%= link_to event.name, event %>
          </td>
          <td class="start_date"><%=l event.start %></td>
          <td><%=l event.end %></td>
          <td><%=l event.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to "Dodaj nowe", new_event_path, class: 'btn btn-primary' %>

app/views/events/new.html.erb
<div class="page-header">
  <h1>Nowe wydarzenie</h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%= icon "bar-chart", @event.name %></h1>
</div>

<div class="row">
  <div class="span4">
    <% if @event.poster_url %>
      <%= image_tag @event.poster_url(:thumb), class: "img-rounded" %>
    <% else %>
      <%= image_tag "thumb.jpg", class: "img-rounded" %>
    <% end %>
  </div>
  <div class="span5">
    <div class="well">
      <div><%= link_to icon("download-alt", "opis"), "#", class: "btn btn-success btn-small", id: "description_btn" %></div>
      <div id="description_info">
        <span class="label label-info">Opis</span>
      </div>
    </div>
    <div class="well">
      <span class="label label-success">Start</span>
      <%=l @event.start %>
    </div>
    <div class="well">
      <span class="label label-important">Koniec</span>
      <%=l @event.end %>
    </div>
  </div>
</div>

<% content_for :sidebar do %>
  <div class="well sidebar-nav">
    <h3><%= icon "cogs", "Panel" %></h3>
    <ul class="nav nav-list">
      <li class="nav-header">Akcje</li>
      <li><%= link_to icon("chevron-left", "Cofnij"), events_path %></li>
      <li><%= link_to icon("edit", "Edytuj"), edit_event_path(@event) %></li>
      <li><%= link_to icon("remove", "Usuń"), event_path(@event), 
        method: 'delete',
        data: { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
      </li>
    </ul>
  </div><!--/.well -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Events" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Events App", root_path, class: "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Wszystkie", events_path  %></li>
              <li><%= link_to "Nowe", new_event_path  %></li>
              <li><%= link_to "Galeria plakatów", gallery_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <%= yield(:sidebar) %>   
            <p>Bogate interfejsy użytkownika &copy; UG 2012</p>
          </div><!--/span-->
        </div><!--/row-->
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>